export const visemeNames = ["aa", "E", "I", "O", "U", "PP", "SS", "TH", "DD", "FF", "kk", "nn", "RR", "CH", "sil"];
export const fbxVisemeNames = ["aa", "E", "ih", "oh", "ou", "PP", "SS", "TH", "DD", "FF", "kk", "nn", "RR", "CH", "sil"];

export const animEmojis = {
  "🙂": { dt: [300, 2000], rescale: [0, 1], vs: { mouthSmile: [0.5] } },
  "😊": { dt: [300, 2000], rescale: [0, 1], vs: { browInnerUp: [0.6], eyeSquintLeft: [1], eyeSquintRight: [1], mouthSmile: [0.7], noseSneerLeft: [0.7], noseSneerRight: [0.7] } },
  "😀": {
    dt: [300, 2000],
    rescale: [0, 1],
    vs: {
      browInnerUp: [0.6],
      jawOpen: [0.1],
      mouthDimpleLeft: [0.2],
      mouthDimpleRight: [0.2],
      mouthOpen: [0.3],
      mouthPressLeft: [0.3],
      mouthPressRight: [0.3],
      mouthRollLower: [0.4],
      mouthShrugUpper: [0.4],
      mouthSmile: [0.7],
      mouthUpperUpLeft: [0.3],
      mouthUpperUpRight: [0.3],
      noseSneerLeft: [0.4],
      noseSneerRight: [0.4],
    },
  },
  "😃": {
    dt: [300, 2000],
    rescale: [0, 1],
    vs: {
      browInnerUp: [0.6],
      eyeWideLeft: [0.7],
      eyeWideRight: [0.7],
      jawOpen: [0.1],
      mouthDimpleLeft: [0.2],
      mouthDimpleRight: [0.2],
      mouthOpen: [0.3],
      mouthPressLeft: [0.3],
      mouthPressRight: [0.3],
      mouthRollLower: [0.4],
      mouthShrugUpper: [0.4],
      mouthSmile: [0.7],
      mouthUpperUpLeft: [0.3],
      mouthUpperUpRight: [0.3],
      noseSneerLeft: [0.4],
      noseSneerRight: [0.4],
    },
  },
  "😄": {
    dt: [300, 2000],
    rescale: [0, 1],
    vs: {
      browInnerUp: [0.3],
      eyeSquintLeft: [1],
      eyeSquintRight: [1],
      jawOpen: [0.2],
      mouthDimpleLeft: [0.2],
      mouthDimpleRight: [0.2],
      mouthOpen: [0.3],
      mouthPressLeft: [0.3],
      mouthPressRight: [0.3],
      mouthRollLower: [0.4],
      mouthShrugUpper: [0.4],
      mouthSmile: [0.7],
      mouthUpperUpLeft: [0.3],
      mouthUpperUpRight: [0.3],
      noseSneerLeft: [0.4],
      noseSneerRight: [0.4],
    },
  },
  "😁": {
    dt: [300, 2000],
    rescale: [0, 1],
    vs: {
      browInnerUp: [0.3],
      eyeSquintLeft: [1],
      eyeSquintRight: [1],
      jawOpen: [0.3],
      mouthDimpleLeft: [0.2],
      mouthDimpleRight: [0.2],
      mouthPressLeft: [0.5],
      mouthPressRight: [0.5],
      mouthShrugUpper: [0.4],
      mouthSmile: [0.7],
      mouthUpperUpLeft: [0.3],
      mouthUpperUpRight: [0.3],
      noseSneerLeft: [0.4],
      noseSneerRight: [0.4],
    },
  },
  "😆": {
    dt: [300, 2000],
    rescale: [0, 1],
    vs: {
      browInnerUp: [0.3],
      eyeSquintLeft: [1],
      eyeSquintRight: [1],
      eyesClosed: [0.6],
      jawOpen: [0.3],
      mouthDimpleLeft: [0.2],
      mouthDimpleRight: [0.2],
      mouthPressLeft: [0.5],
      mouthPressRight: [0.5],
      mouthShrugUpper: [0.4],
      mouthSmile: [0.7],
      mouthUpperUpLeft: [0.3],
      mouthUpperUpRight: [0.3],
      noseSneerLeft: [0.4],
      noseSneerRight: [0.4],
    },
  },
  "😂": {
    dt: [300, 2000],
    rescale: [0, 1],
    vs: {
      browInnerUp: [0.3],
      eyeSquintLeft: [1],
      eyeSquintRight: [1],
      eyesClosed: [0.6],
      jawOpen: [0.3],
      mouthDimpleLeft: [0.2],
      mouthDimpleRight: [0.2],
      mouthPressLeft: [0.5],
      mouthPressRight: [0.5],
      mouthShrugUpper: [0.4],
      mouthSmile: [0.7],
      mouthUpperUpLeft: [0.3],
      mouthUpperUpRight: [0.3],
      noseSneerLeft: [0.4],
      noseSneerRight: [0.4],
    },
  },
  "🤣": { link: "😂" },
  "😅": { link: "😂" },
  "😭": {
    dt: [1000, 1000],
    rescale: [0, 1],
    vs: {
      browInnerUp: [1],
      eyeSquintLeft: [1],
      eyeSquintRight: [1],
      eyesClosed: [0.1],
      jawOpen: [0],
      mouthFrownLeft: [1],
      mouthFrownRight: [1],
      mouthOpen: [0.5],
      mouthPucker: [0.5],
      mouthUpperUpLeft: [0.6],
      mouthUpperUpRight: [0.6],
    },
  },
  "🥺": {
    dt: [1000, 1000],
    rescale: [0, 1],
    vs: {
      browDownLeft: [0.2],
      browDownRight: [0.2],
      browInnerUp: [1],
      eyeWideLeft: [0.9],
      eyeWideRight: [0.9],
      eyesClosed: [0.1],
      mouthClose: [0.2],
      mouthFrownLeft: [1],
      mouthFrownRight: [1],
      mouthPressLeft: [0.4],
      mouthPressRight: [0.4],
      mouthPucker: [1],
      mouthRollLower: [0.6],
      mouthRollUpper: [0.2],
      mouthUpperUpLeft: [0.8],
      mouthUpperUpRight: [0.8],
    },
  },

  "☹️": { dt: [500, 1500], rescale: [0, 1], vs: { mouthFrownLeft: [1], mouthFrownRight: [1], mouthPucker: [0.1], mouthRollLower: [0.8] } },
  "😚": {
    dt: [500, 1000, 1000],
    rescale: [0, 1, 0],
    vs: {
      browInnerUp: [0.6],
      eyeBlinkLeft: [1],
      eyeBlinkRight: [1],
      eyeSquintLeft: [1],
      eyeSquintRight: [1],
      mouthPucker: [0, 0.5],
      noseSneerLeft: [0, 0.7],
      noseSneerRight: [0, 0.7],
      viseme_U: [0, 1],
    },
  },
  "🥰": { dt: [1000, 1000], rescale: [0, 1], vs: { browInnerUp: [0.6], eyeSquintLeft: [1], eyeSquintRight: [1], mouthSmile: [0.7], noseSneerLeft: [0.7], noseSneerRight: [0.7] } },
  "😍": {
    dt: [1000, 1000],
    rescale: [0, 1],
    vs: {
      browInnerUp: [0.6],
      jawOpen: [0.1],
      mouthDimpleLeft: [0.2],
      mouthDimpleRight: [0.2],
      mouthOpen: [0.3],
      mouthPressLeft: [0.3],
      mouthPressRight: [0.3],
      mouthRollLower: [0.4],
      mouthShrugUpper: [0.4],
      mouthSmile: [0.7],
      mouthUpperUpLeft: [0.3],
      mouthUpperUpRight: [0.3],
      noseSneerLeft: [0.4],
      noseSneerRight: [0.4],
    },
  },
  "🤩": { link: "😍" },
  "😱": { dt: [500, 1500], rescale: [0, 1], vs: { browInnerUp: [0.8], eyeWideLeft: [0.5], eyeWideRight: [0.5], jawOpen: [0.7], mouthFunnel: [0.5] } },
  "😬": {
    dt: [500, 1500],
    rescale: [0, 1],
    vs: {
      browDownLeft: [1],
      browDownRight: [1],
      browInnerUp: [1],
      mouthDimpleLeft: [0.5],
      mouthDimpleRight: [0.5],
      mouthLowerDownLeft: [1],
      mouthLowerDownRight: [1],
      mouthPressLeft: [0.4],
      mouthPressRight: [0.4],
      mouthPucker: [0.5],
      mouthSmile: [0.1],
      mouthSmileLeft: [0.2],
      mouthSmileRight: [0.2],
      mouthStretchLeft: [1],
      mouthStretchRight: [1],
      mouthUpperUpLeft: [1],
      mouthUpperUpRight: [1],
    },
  },
};
