/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppKitButton: typeof import('./../components/AppKitButton.vue')['default']
    Audio: typeof import('./../components/Audio.vue')['default']
    Button: typeof import('./../components/Button.vue')['default']
    Card_pagination: typeof import('./../components/Card_pagination.vue')['default']
    CollapsibleText: typeof import('./../components/CollapsibleText.vue')['default']
    DragUpload: typeof import('./../components/DragUpload.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Empty: typeof import('./../components/Empty.vue')['default']
    FormItem: typeof import('./../components/FormItem.vue')['default']
    Lang: typeof import('./../components/Lang.vue')['default']
    Logo: typeof import('./../components/logo.vue')['default']
    MainPage: typeof import('./../components/mainPage.vue')['default']
    Menu: typeof import('./../components/menu.vue')['default']
    Navbar: typeof import('./../components/navbar.vue')['default']
    NoUsername: typeof import('./../components/NoUsername.vue')['default']
    Pagination: typeof import('./../components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../components/Search.vue')['default']
    Setup: typeof import('./../components/Setup.vue')['default']
    Swiper: typeof import('./../components/Swiper.vue')['default']
    Tabs: typeof import('./../components/Tabs.vue')['default']
    Theme: typeof import('./../components/Theme.vue')['default']
    UserInfo: typeof import('./../components/UserInfo.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
